connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *connection
  database: product_api_development
  username: postgres
  password: root

test:
  <<: *connection
  database: product_api_test

production:
  <<: *connection
  database: product_api_production